### PR TITLE
Changed static readonly tag to const

### PR DESCRIPTION
**Pull request by pekaram**
const is a better fit here and would allow using those values in a switch

### CODE REVIEW

**Comment by JamJar00** [comment]
Cheers for the pull request!

`const` and `readonly` have some subtle differences beyond this. A readonly field is actually a real field which is referenced whereas `const` causes the compiler to replace any usages with the value during compilation, which means `const` can't be accessed across assemblies where `readonly` fields can.

Some users do keep their tags in separate assemblies for common server-client code and would want a `readonly` field, others would probably prefer to use a switch statement. Eitherway, a user will find the right solution for them from a quick Google to be honest.

It's kind of annoying that `Tags` is now instantiatable, can it be left as a static class or is that a syntax error with `const` because it's not 'static'?

I'm not sure I see massive value in this change personally. If we go for it we'll need to update the completed examples [here](https://github.com/DarkRiftNetworking/AgarUnityComplete/blob/master/Assets/Tags.cs) and [here](https://github.com/DarkRiftNetworking/AgarPluginComplete/blob/master/AgarPlugin/Tags.cs) as well.

**Comment by JamJar00** [comment]
It also still says 'and put in a **static** class' in the line above your changes!

**Comment by pekaram** [comment]
It still "can" be accessed across assemblies. Only that it would be represented by value. I personally see the switch that indexes all tags/event types as the cleanest/most perfomant approach.

**Comment by pekaram** [comment]
Remember the only issue is: if you messed up their numerical indexes, then you have to rebuild the solution

**Comment by pekaram** [comment]
Static class can have const.

**Comment by pekaram** [comment]
> It also still says 'and put in a **static** class' in the line above your changes!

It still can be static, I just didn't see that one =D

**Comment by pekaram** [comment]
But I get your point, it's just that for me it's "performance by default" in game development

**Comment by JamJar00** [comment]
I'd normally agree with performance being the key thing, but I'm not quite as bothered here because this is really a beginner tutorial and we're not actually showing the `const` field being used in a switch at any point.

**Comment by pekaram** [comment]
I see your point. Also people nowdays are looking for easy turnkey solutions to get into multiplayer, so an easy tutorial is critical indeed. 

On another note, DarkRift is impressive

**Pull request closed without merging**
